name: RubyLove
url: http://rubylove.io
subheading: Functional Ruby, Code Beauty, and Ruby Internals
keywords: functional programming, functional ruby, idiomatic ruby, ruby internals, testing practices
title: Functional Programming in Ruby, Ruby Internals, Ruby API, Concurrency in Ruby, Ruby without Rails) - RubyLove
markdown: redcarpet
permalink: /:categories/:year/:month/:day/:title/
pygments: true
comments:
  provider: disqus
  disqus:
    short_name: thatrubylove

