name: CodeCatalyst
url: http://chenzhiyong.yumumu.me
subheading: “别活得太认真，你逃不出你的命运。” – Van Wilder
keywords: 编程，算法
title: CodeCatalyst
markdown: redcarpet
permalink: /:categories/:year/:month/:day/:title/
pygments: true
comments:
  provider: disqus
  disqus:
    short_name: CodeCatalyst

